server:
  port: 8080

spring:
  datasource:
    username: QuickFile
    password: d.d.1999
    url: jdbc:mysql://148.70.157.68:3306/QuickFile
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.diaosu.entity

external:
 wechat:
   openid:
     url: https://api.weixin.qq.com/sns/jscode2session
     appid: wxed4d3801c1847135
     appsecret: 483c7b06da3fb23d692146b783942717

#showSql
logging:
  level:
    com:
      diaosu:
        mapper: debug
